export var ViewConstants = {
  Dashboard: "Dashboard",
  Tasks: "Tasks",
  Projects: "Projects",
  Workgroups: "Workgroups",
  Notifications: "Notifications",
  Search: "Search",
  Chats: "Chats",
  Video_Calls: "Video Calls",
  Audio_Calls: "Audio Calls",
  Make_Video_Calls: "Make Video Calls",
  Make_Audio_Calls: "Make Audio Calls",
  Conferencing: "Conferencing",
  Office_Mail: "Office Mail",
  My_Signature: "My Signature",
  Document_Template: "Document Template",
  Organization: "Organization",
  Business_Intelligence: "Business Intelligence",
  Drive: "Drive",
  Issues_Tracking: "Issues Tracking",
  Screen_Sharing: "Screen Sharing",
  Calendar: "Calendar",
  Settings: "Settings",
};
